export const transactionData = [
    {
        id: 1,
        service: "Care services",
        status: "success",
        createdAt: "25 August 2024",
        amount: "12000",
        type: "debit",
    },
    {
        id: 2,
        service: "Account funding",
        status: "denied",
        createdAt: "25 August 2024",
        amount: "120000",
        type: "credit",
    },
    {
        id: 3,
        service: "Care services",
        status: "denied",
        createdAt: "25 September 2024",
        amount: "12000",
        type: "debit",
    },
    {
        id: 4,
        service: "Account funding",
        status: "success",
        createdAt: "25 October 2024",
        amount: "120000",
        type: "credit",
    },
    {
        id: 5,
        service: "Care services",
        status: "success",
        createdAt: "25 August 2024",
        amount: "12000",
        type: "debit",
    },
    // {
    //     id: 6,
    //     service: "Account funding",
    //     status: "denied",
    //     createdAt: "25 August 2024",
    //     amount: "120000",
    //     type: "credit",
    // },
    // {
    //     id: 7,
    //     service: "Care services",
    //     status: "denied",
    //     createdAt: "25 September 2024",
    //     amount: "12000",
    //     type: "debit",
    // },
    // {
    //     id: 8,
    //     service: "Account funding",
    //     status: "success",
    //     createdAt: "25 October 2024",
    //     amount: "120000",
    //     type: "credit",
    // },
    // {
    //     id: 9,
    //     service: "Care services",
    //     status: "success",
    //     createdAt: "25 August 2024",
    //     amount: "12000",
    //     type: "debit",
    // },
    // {
    //     id: 10,
    //     service: "Account funding",
    //     status: "denied",
    //     createdAt: "25 August 2024",
    //     amount: "120000",
    //     type: "credit",
    // },

]